### ISSUE TITLE
References to MoNTE48's library forks

### ISSUE THREAD

**Issue by celeron55** [minetest/minetest_android_deps_binaries#1]
There are some references to MoNTE48's forked or distributed libraries in the build scripts that should probably be modified to refer to the original libraries and apply patches to them if needed.

https://github.com/minetest/minetest_android_deps_binaries/blob/b1672489a6cabc4bcf784ffa9e362aa465b36b60/Android/Build/Makefile#L81

~~github.com/minetest/minetest_android_deps_binaries/blob/b1672489a6cabc4bcf784ffa9e362aa465b36b60/Android/Build/Makefile#L88~~ (Irrlicht, now superseded)

Possibly only these two.

**Comment by MoNTE48** [comment]
libvorbis and libogg do not have Android support. Also, libvorbis has a lot of unnecessary for Minetest, which significantly increases the size of the binary file.
My fork is based on the latest version of the code, with some fixes and an integrated Android build system. It also combines libogg into a libvorbis binary file and removes all non-ogg format support.
In addition, you have already used third-party forks for many years.

Proof:
1) Openalsoft https://github.com/minetest/minetest/blob/master/build/android/Makefile#L78
unknown developer, last updated on 18 Jul 2013. Released 7 years ago.
2) Vorbis+Ogg https://github.com/minetest/minetest/blob/master/build/android/Makefile#L85
A very old fork of vorbis, then you fork it again. Based on libvorbis on Aug 16, 2014. Released 6 years ago
3) Freetype2 https://github.com/minetest/minetest/blob/master/build/android/Makefile#L113
unknown developer, last updated on 16 Aug 2011. Sh*t! Released 9 years ago!!!
---
Any complaints about my code? I read the IRC, by the way.

If you will notice, MultiCraft suggested building openal-soft and freetype2 directly from the source.
Building from a source separately libvorbis, separately libogg with patches will only increase the size of the binary file, increase the complexity of the build system, and increase the likelihood that this will break when a new version is released.

Irrlicht another conversation, do what you want.
