### ISSUE TITLE
Update Notification

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest_android_deps_binaries#2]
**1) Android: mbedTLS 2.16.5 (armeabi-v7a, arm64-v8a)**
https://github.com/MultiCraft/deps/commit/ee18e9a490db931d3fa4729d647d8adaeebbcbbe

**2) Android: Update Curl 7.69.1 (armeabi-v7a, arm64-v8a)**
https://github.com/MultiCraft/deps/commit/12c5433c4f4277a1f1d16b5be905a742b7c9b04b

**3) Android: Update build Makefile (Add OpenSSL, mbedTLS and cleanup)**
https://github.com/MultiCraft/deps/commit/9ef8cfbffc75e1c39f5c072bc3656d248594ddde

* Added (disabled) OpenSSL 
* Added lightweight mbedTLS
* Updated libCurl with mbedTLS support
* Clarify used OpenAL-soft version
* Cleanup and fix code-style

***
Core Devs chose to fork my repository. I will not fork my fork, for offering PRs and resolve conflicts. I just inform that I built an update of some library or released fixes / improvements to the build script.
Of course, Core Devs can easily redo all this, and do much better than me. If they ever find the time :)

**Comment by rubenwardy** [comment]
Done! I've watched the upstream repo, but I don't think that notifies on commit pushes

I intend to set up an alternative to this that builds the dependencies using scripts to ensure that the builds are reproducible - reproducible builds are important to transparency in open source, and using a pipeline to build dependencies ensures this

**Comment by MoNTE48** [comment]
Thanks. Yes, if it were built using some kind of buildbot, with the ability to download binary files from there, that would be cool.
Git is a terrible way to store and distribute binary files. But this is the first thing that occurred to me when I was looking for where to place them so that gradle could easily load them on Windows!
